### ISSUE TITLE
Question about the contents of imagenet.categories

### ISSUE THREAD

**Issue by sbite0138** [moskomule/dataset-contamination#1]
Hello. Thank you for sharing your implementation.

I am currently trying to generate my own SD-ImageNet equivalent dataset using this implementation.
[In the sd_imagenet.py](https://github.com/moskomule/dataset-contamination/blob/main/src/sd_imagenet.py#L203-L204) , there is a process that accesses a file named `imagenet.categories` and generates prompts using its contents.
Could you please tell me the contents of the file about this `imagenet.categories`?

Thanks in advance.

**Comment by moskomule** [comment]
Hi! `imagenet.categories` in `sd_imagenet.py` is from https://github.com/pytorch/vision/blob/main/torchvision/prototype/datasets/_builtin/imagenet.categories#L50.

**Comment by sbite0138** [comment]
Thanks for your reply.
> imagenet.categories in sd_imagenet.py is from https://github.com/pytorch/vision/blob/main/torchvision/prototype/datasets/_builtin/ imagenet.categories#L50.

I see. thank you !
